### ISSUE TITLE
How to install extensions, such as hstore?

### ISSUE THREAD

**Issue by hakunin** [guedes/pgvm#47]
Hi, how do I install extensions, such as hstore?

**Comment by lucasdavila** [comment]
Hi @hakunin !

Install pg extensions is pretty simple, I have a blog post about it [1], but since it is in Portuguese I will list the commands you need to run :smile_cat: 

First run these commands in the machine where pgvm is installed:
* `cd ~/.pgvm/src/postgresql-x.y.z/contrib`
* `make` 
* `make install` 
* `make installcheck` 

And then just run this sql:
* `CREATE EXTENSION IF NOT EXISTS hstore;`

It should be enough to install the hstore extension, and any other extension from the contrib package (you just need to change the extension name in the end of the sql command).

I hope I have helped you :)

[1] http://blog.lucasdavi.la/post/2012/9/12/instalando-modulos-contrib-do-postgresql

**Comment by hakunin** [comment]
Oh thats fantastic, thanks! I am using pgvm form now on :)

**Comment by hakunin** [comment]
For people like me, who're used to installing postgres once a year through brew, it would nice to include this in the readme.

**Comment by hakunin** [comment]
Have compiled the contrib and hstore works, but uuid-ossp doesn't, any tips?

ERROR:  could not open extension control file "/Users/michal/.pgvm/environments/9.3.5/share/postgresql/extension/uuid-ossp.control": No such file or directory
: CREATE EXTENSION IF NOT EXISTS "uuid-ossp"

**Comment by hakunin** [comment]
Just installed 9.4.4 and apart from the install check complaining I was able to make the extensions running once I created a new cluster.

**Comment by guedes** [comment]
Nice! Thanks!

**Comment by bitboxer** [comment]
For everyone reading this and curious on how to install uuid-ossp:

```
cd ~/.pgvm/src/postgresql-x.y.z
./configure --with-uuid=e2fs --prefix ~/.pgvm/environments/x.y.z/
cd contrib
make
make install
```

**Comment by nisanthchunduru** [comment]
Can't pgvm install extensions by default like homebrew's postgres formula does

**Comment by hakunin** [comment]
None of these work for me anymore (at least on ubuntu). Any alternatives to pgvm?
